# Each config specifies multiple fields to be extracted from the csv.
# Each field must specify both bins and domain.
# Fields may optionally specify an value_map.
#
# bins - Number of bins, or an explicit division of bins given as
#        a list of bin boundaries. This is given as an argument to
#        numpy.histogramdd.
#
# domain - The overall domain for the field, provided either as
#          a list [lower bound, upper bound] or the string 'active',
#          which indicates the active domain should be used. If a
#          domain isn't provided the active domain will be used.
#
# value_map (optional) - A dictionary that maps non-numerical
#                       field values to a number so that they can be
#                       properly added to a histogram.
age: 
    type: discrete
    bins: 85
    domain: [16,100]
workclass: 
    type: categorical
    bins: 9
    domain: [0,8]
    value_map: 
        Private: 0 
        Self-emp-not-inc: 1 
        Self-emp-inc: 2
        Federal-gov: 3 
        Local-gov: 4 
        State-gov: 5
        Without-pay: 6
        Never-worked: 7
        ?: 8
fnlwgt: 
    type: discrete
    bins: 100
    domain: [10000, 1500000]
education: 
    type: categorical
    bins: 16
    domain: [0,15]
    value_map:
        Bachelors: 0 
        Some-college: 1 
        11th: 2
        HS-grad: 3
        Prof-school: 4
        Assoc-acdm: 5
        Assoc-voc: 6
        9th: 7
        7th-8th: 8
        12th: 9
        Masters: 10
        1st-4th: 11
        10th: 12
        Doctorate: 13
        5th-6th: 14
        Preschool: 15
education-num: 
    type: discrete
    bins: 16
    domain: [1,16]
marital-status: 
    type: categorical
    bins: 7
    domain: [0,6]
    value_map:
        Married-civ-spouse: 0
        Divorced: 1
        Never-married: 2 
        Separated: 3
        Widowed: 4
        Married-spouse-absent: 5
        Married-AF-spouse: 6
occupation: 
    type: categorical
    bins: 15
    domain: [0,14]
    value_map:
        Tech-support: 0 
        Craft-repair: 1
        Other-service: 2
        Sales: 3
        Exec-managerial: 4
        Prof-specialty: 5
        Handlers-cleaners: 6
        Machine-op-inspct: 7
        Adm-clerical: 8
        Farming-fishing: 9
        Transport-moving: 10
        Priv-house-serv: 11
        Protective-serv: 12
        Armed-Forces: 13
        ?: 14
relationship: 
    type: categorical
    bins: 6
    domain: [0,5]
    value_map:
        Wife: 0
        Own-child: 1
        Husband: 2
        Not-in-family: 3
        Other-relative: 4
        Unmarried: 5
race: 
    type: categorical
    bins: 5
    domain: [0,4]
    value_map:
        White: 0 
        Asian-Pac-Islander: 1
        Amer-Indian-Eskimo: 2
        Other: 3
        Black: 4
sex: 
    type: categorical
    bins: 2
    domain: [0,1]
    value_map:
        Female: 0
        Male: 1
capital-gain:
    bins: 100
    domain: [0,100000]
    type: discrete
capital-loss:
    type: discrete
    bins: 100
    domain: [0,5000]
hours-per-week:
    type: discrete
    bins: 99
    domain: [1,99]
native-country:
    type: categorical
    bins: 42
    domain: [0,41]
    value_map:
        United-States: 0 
        Cambodia: 1
        England: 2
        Puerto-Rico: 3
        Canada: 4
        Germany: 5
        Outlying-US(Guam-USVI-etc): 6
        India: 7
        Japan: 8
        Greece: 9
        South: 10
        China: 11
        Cuba: 12
        Iran: 13
        Honduras: 14
        Philippines: 15 
        Italy: 16
        Poland: 17
        Jamaica: 18
        Vietnam: 19
        Mexico: 20
        Portugal: 21
        Ireland: 22
        France: 23
        Dominican-Republic: 24
        Laos: 25
        Ecuador: 26 
        Taiwan: 27
        Haiti: 28
        Columbia: 29 
        Hungary: 30
        Guatemala: 31
        Nicaragua: 32
        Scotland: 33
        Thailand: 34
        Yugoslavia: 35
        El-Salvador: 36
        Trinadad&Tobago: 37
        Peru: 38
        Hong: 39
        Holand-Netherlands: 40
        ?: 41
income>50K:
    type: categorical
    bins: 2
    domain: [0,1]
    value_map:
        <=50K: 0
        '>50K': 1
